# Altere o programa anterior, intercalando 3 vetores de 10 elementos cada.

In [1]:
from random import randint
import numpy as np

In [2]:
a = np.array([randint(0, 9) for _ in range(10)])
b = np.array([randint(0, 9) for _ in range(10)])
c = np.array([randint(0, 9) for _ in range(10)])
d = np.array([a, b, c])

In [3]:
print(a)
print(b)
print(c)

[0 2 7 2 5 9 6 4 8 9]
[2 3 4 1 2 1 3 8 4 8]
[6 3 4 6 8 3 7 3 5 5]


In [4]:
print(d.T)

[[0 2 6]
 [2 3 3]
 [7 4 4]
 [2 1 6]
 [5 2 8]
 [9 1 3]
 [6 3 7]
 [4 8 3]
 [8 4 5]
 [9 8 5]]
