# Faça um Programa que leia dois vetores com 10 elementos cada. Gere um terceiro vetor de 20 elementos, cujos valores deverão ser compostos pelos elementos intercalados dos dois outros vetores.

In [29]:
from random import randint
import numpy as np

In [39]:
a = np.array([randint(0, 9) for _ in range(10)])
b = np.array([randint(0, 9) for _ in range(10)])
c = np.array([a, b])

In [40]:
print(a)
print(b)

[5 0 9 4 9 8 4 3 6 7]
[4 9 0 2 9 0 1 9 8 8]


In [41]:
print(c.T)

[[5 4]
 [0 9]
 [9 0]
 [4 2]
 [9 9]
 [8 0]
 [4 1]
 [3 9]
 [6 8]
 [7 8]]
